### ISSUE TITLE
Adding the option to do last X posts on the home page

### ISSUE THREAD

**Issue by moshe742** [szabgab/code-maven.rs#39]
I would like to be able to put in the home page in addition to some info about myself (or without it) links for the last X posts in my blog
So, for example, I can have the last 10 posts featured on the home page.
As more customization one can think about random posts or tag related posts to be featured, but I think we can start with last X posts

**Comment by szabgab** [comment]
I think the way this could be added is by starting to support embedding tags e.g. putting

```
{% latest count=10 %}
```

in a markdown file would list the title of the 10 most recent posts.


then maybe 
```
{% latest count=10 tag=python  %}
```

Would show the 10 most recent posts with `python` tag.

**Comment by szabgab** [comment]
This has been implemented using the following format:

```
{% latest limit=5  %}
```

```
{% latest limit=3 tag=programming  %}
```

Please verify.

**Comment by szabgab** [comment]
Since then I changed it a bit, there need to be a quote around the non-numerical value:

`{% latest limit=3 tag="programming" %}`

**Comment by moshe742** [comment]
It works with quotes, thanks

**Comment by szabgab** [comment]
Thanks for confirming and sorry for the update :-) 

I keep the definitions here: https://ssg.code-maven.com/special-syntax
