### ISSUE TITLE
Getting an error after adding file and changing configuration

### ISSUE THREAD

**Issue by moshe742** [szabgab/code-maven.rs#40]
I try to use the web command

    $ ../../code-maven web

I get an error after adding a new file to pages and change either the authors nickname in the config.yaml or the author in the file I added in pages (or both) I get the following error:

    thread 'main' panicked at src/web.rs:365:16:
    index out of bounds: the len is 0 but the index is 0
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I would expect either to get a more descriptive error message or better yet, will work regardless
If you want me to run the command again with backtrace let me know (and if you prefer me to put there 1 or full)

**Comment by szabgab** [comment]
Indeed it is cause by having an author nickname in one of the md files that is missing from the config file. I'll fix the code to give a clear indication of this instead of just crashing.

The solution on your side is to make sure each author mentioned in the pages has an entry in the config file.

**Comment by szabgab** [comment]
The new version should give you a better error message. Please verify and let me know.

**Comment by moshe742** [comment]
Verified, gives an error that explains what is the problem, thanks
